from __future__ import annotations

MAX_PORT = 65535
FILE_MODE_PRIVATE = 0o600
BABEL_DEFAULT_RXCOST = 120
WG_PORT_RANGE = (20000, 65535)
NET_BACKEND_NETWORKD = "networkd"
NET_BACKEND_NM = "nm"
IFNAME_PREFIX_BGP = "dn42_"
IFNAME_PREFIX_IBGP = "wg_"
LIVE_CMD_TIMEOUT = 2
